// <auto-generated />
using System;
using GadjIT_ClientContext.P4W;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GadjIT_ClientContext_Proj.Migrations
{
    [DbContext(typeof(P4W_Context))]
    [Migration("20221111115939_Initial003")]
    partial class Initial003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GadjIT_ClientContext.P4W.CaseTypeGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UC_CaseTypeGroups_Name")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("CaseTypeGroups");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.CaseTypes", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArchiveDays")
                        .HasColumnType("int");

                    b.Property<string>("ArchiveLocation")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("(null)");

                    b.Property<int?>("ArchiveMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<bool>("AutoCreateCaseTheLinkApp")
                        .HasColumnType("bit");

                    b.Property<int?>("CaseTypeGroupRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int>("CmportalType")
                        .HasColumnType("int")
                        .HasColumnName("CMPortalType");

                    b.Property<string>("CodeName")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<bool?>("ComplianceCentre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("ComplianceHighValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<short?>("DefaultDestroyYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("DefaultPasagenda")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DefaultPASAgenda");

                    b.Property<byte>("DefaultUtbmsbudgetLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("DefaultUTBMSBudgetLevel");

                    b.Property<string>("DefaultUtbmscodeSet")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DefaultUTBMSCodeSet")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("DefaultUtbmsphaseTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("DefaultUTBMSPhaseTemplateID");

                    b.Property<int>("DefaultUtbmstaskTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("DefaultUTBMSTaskTemplateID");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EnableLitigation")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableSdlt")
                        .HasColumnType("bit")
                        .HasColumnName("EnableSDLT");

                    b.Property<byte>("EnableUtbmscoding")
                        .HasColumnType("tinyint")
                        .HasColumnName("EnableUTBMSCoding");

                    b.Property<byte?>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("InitialAgendaName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IsokonCaseType")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ManFieldsMore")
                        .HasColumnType("int");

                    b.Property<int?>("MaxConsequenceRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("max_consequence_rating")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("Mpview")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MPView");

                    b.Property<bool?>("NetDocsSync")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("NextFileNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(1)");

                    b.Property<int?>("RetentionMonths")
                        .HasColumnType("int");

                    b.Property<byte?>("Samallowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("SAMAllowed")
                        .HasDefaultValueSql("(0)");

                    b.Property<bool>("TheLinkApp")
                        .HasColumnType("bit");

                    b.Property<int?>("WebPublish")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .IsClustered(false);

                    b.HasIndex("CodeName")
                        .IsUnique()
                        .HasDatabaseName("UC_CaseTypes_CodeName")
                        .HasFilter("[CodeName] IS NOT NULL");

                    b.ToTable("CaseTypes");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.DmDocuments", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActionOnComplete")
                        .HasColumnType("int");

                    b.Property<int?>("ActionOnOverdue")
                        .HasColumnType("int");

                    b.Property<byte>("ActionOnTake")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("Actioned")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.Property<bool?>("AlwaysSpecial")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.Property<short?>("AutoEmail")
                        .HasColumnType("smallint");

                    b.Property<byte?>("AutoTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("CanTake")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("CaseTypeGroupRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("ChequeReq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("ConsequenceRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedByRef")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int?>("Critical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<DateTime?>("DateAmended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DefaultMacro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("DefaultProgressFile")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Deleteble")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(1)");

                    b.Property<byte>("DisableAutoPrint")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int>("DurationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("EmailTemplate")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("FeeDiaryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("FeeDiaryText")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Flags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<decimal?>("FlatFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("InstDiaryText")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IntsDiaryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Locked")
                        .HasColumnType("tinyint");

                    b.Property<int>("MainClassId")
                        .HasColumnType("int")
                        .HasColumnName("MainClassID");

                    b.Property<byte?>("Mandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<byte>("MandatoryDefaultMacro")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MultiMatter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NoOfCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(1)");

                    b.Property<int?>("NoUnassignedGroupEntries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("OutputType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("PartDiaryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("PartDiaryText")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PdfhtmlemailTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PDFHTMLEmailTemplate")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int>("PdfstationerySetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PDFStationerySetID")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int?>("ReminderDocumentRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("RenameDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasDefaultValueSql("('')");

                    b.Property<byte>("RenamePromptUser")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Replicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(1)");

                    b.Property<int?>("Samaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SAMAction")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("Sammacro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SAMMacro")
                        .HasDefaultValueSql("(0)");

                    b.Property<int>("Sampriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SAMPriority")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("ShowTakePrintEmailPrompt")
                        .HasColumnType("tinyint");

                    b.Property<string>("StepCategory")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("SubClassId")
                        .HasColumnType("int")
                        .HasColumnName("SubClassID");

                    b.Property<int?>("SupDiaryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("SupDiaryText")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("TakeToPdf")
                        .HasColumnType("tinyint")
                        .HasColumnName("TakeToPDF");

                    b.Property<byte?>("TemplateEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<bool>("TheLinkApp")
                        .HasColumnType("bit");

                    b.Property<string>("UserHelp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<int?>("VersionControl")
                        .HasColumnType("int");

                    b.Property<int?>("WebPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.HasKey("Code")
                        .IsClustered(false);

                    b.ToTable("Dm_Documents");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.DmDocumentsPermissions", b =>
                {
                    b.Property<int>("Doccode")
                        .HasColumnType("int")
                        .HasColumnName("doccode");

                    b.Property<int>("Casetype")
                        .HasColumnType("int")
                        .HasColumnName("casetype");

                    b.HasKey("Doccode", "Casetype")
                        .HasName("PK__DM_DocumentsPerm__1F7A4DDE");

                    b.ToTable("DM_DocumentsPermissions");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.MpSysViews", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CaseGroupRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<byte>("CrmLinked")
                        .HasColumnType("tinyint")
                        .HasColumnName("CRM_Linked");

                    b.Property<int?>("DescriptionField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<byte?>("Designable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(1)");

                    b.Property<int?>("Flags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("Form")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("InternalName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(3000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NextItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("ReadLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<byte?>("System")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("SystemName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("('')");

                    b.Property<int?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.Property<int?>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visibility")
                        .HasDefaultValueSql("(1)");

                    b.Property<byte>("WebPublish")
                        .HasColumnType("tinyint");

                    b.Property<int?>("WriteLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(0)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.ToTable("Mp_Sys_Views");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.TableDate", b =>
                {
                    b.Property<string>("TableField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableType")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("GadjIT_ClientContext.P4W.UsrOrsfSmartflows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CaseTypeGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("SeqNo")
                        .HasColumnType("int");

                    b.Property<string>("SmartflowData")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SmartflowName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("VariantName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("VariantNo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.ToTable("Usr_ORSF_Smartflows");
                });
#pragma warning restore 612, 618
        }
    }
}
