using System;
using System.Collections.Generic;

namespace Gizmo_V1._00.Models
{
    public partial class UsrOrResiMt
    {
        public string EntityRef { get; set; }
        public int MatterNo { get; set; }
        public string DataValidatedSuccessfully { get; set; }
        public string JointClientSalutation { get; set; }
        public string JointOwnership { get; set; }
        public string CarePackStatus { get; set; }
        public DateTime? DateCarePackReceived { get; set; }
        public string WriteToClient2Separately { get; set; }
        public string SearchAgentEmailAddress { get; set; }
        public int Id { get; set; }
        public string EstateAgentsRef { get; set; }
        public string Solicitorsref { get; set; }
        public string SellerRef { get; set; }
        public string SearchProviderRef { get; set; }
        public string ManagingAgentRef { get; set; }
        public string SourceOfIntroductionRef { get; set; }
        public decimal? TotalFees { get; set; }
        public decimal? TotalFeesPaid { get; set; }
        public decimal? TotalFeesUnpaid { get; set; }
        public DateTime? AnticipatedCompletionDate { get; set; }
        public DateTime? ExchangeDate { get; set; }
        public string NameOfPersonExchangedWith { get; set; }
        public string CompletionOnNotice { get; set; }
        public string Exchanged { get; set; }
        public string ExchangeCallNotes { get; set; }
        public DateTime? PreferredCompletionDate { get; set; }
        public decimal? TotalChattels { get; set; }
        public decimal? TotalMoa { get; set; }
        public decimal? TotalApportionments { get; set; }
        public decimal? TotalDisbs { get; set; }
        public decimal? TotalDisbsPaid { get; set; }
        public decimal? TotalDisbsUnpaid { get; set; }
        public decimal? TotalSearches { get; set; }
        public decimal? TotalSearchesPaid { get; set; }
        public decimal? TotalSearchesUnpaid { get; set; }
        public string PostingSlipMessage { get; set; }
        public string LinkedCaseExists { get; set; }
        public decimal? TotalApportionmentsOverpaid { get; set; }
        public decimal? TotalApportionmentsUnderpaid { get; set; }
        public DateTime? CompletionDate { get; set; }
        public decimal? CompletionFees { get; set; }
        public decimal? CompletionDisbs { get; set; }
        public decimal? CompletionOtherCosts { get; set; }
        public decimal? CompletionReceipts { get; set; }
        public decimal? CompletionBalance { get; set; }
        public decimal? TotalFundsAvailable { get; set; }
        public decimal? TotalMoaForDisbs { get; set; }
        public decimal? TotalFundsShortfall { get; set; }
        public decimal? CompletionTotalCosts { get; set; }
        public decimal? MortgageAdvanceAmount { get; set; }
        public decimal? MortgageRedemption { get; set; }
        public decimal? SaleProceeds { get; set; }
        public decimal? DepositAmount { get; set; }
        public string MortgageRedemptionPostingSlip { get; set; }
        public DateTime? MortgageRedemptionDateFundsSentToLender { get; set; }
        public decimal? PurchasePrice { get; set; }
        public decimal? SalePrice { get; set; }
        public decimal? RetentionAmount { get; set; }
        public string MortgageRedemptionExisitingMortgageToRedeem { get; set; }
        public string LenderPurchase { get; set; }
        public string LenderSale { get; set; }
        public string LenderSale1 { get; set; }
        public string LenderPurchase1 { get; set; }
        public string ContactRef { get; set; }
        public string DepositIs10Percent { get; set; }
        public string DepositType { get; set; }
        public string SlipPayOutMethodDeposit { get; set; }
        public string SlipPayOutMethodBalance { get; set; }
        public string SlipPayOutMethodRedemption { get; set; }
        public string SlipPayInMethodAdvance { get; set; }
        public string SlipPayInMethodSaleProceeds { get; set; }
        public decimal? CompletionFunds { get; set; }
        public string OnHoldYn { get; set; }
        public decimal? TotalFundsPending { get; set; }
        public decimal? TotalFundsReceived { get; set; }
        public decimal? TotalFundsCleared { get; set; }
        public decimal? TotalDisbsAnticipated { get; set; }
        public string TenDayCoolingOffPeriodWaivered { get; set; }
        public decimal? EstateAgentBillAmount { get; set; }
        public string EstateAgentBillReceived { get; set; }
        public decimal? LeaseholdPackFee { get; set; }
        public string LeaseholdPackChargeApplicable { get; set; }
        public string LeaseholdPackRequestedFrom { get; set; }
        public int? RedemptionTotalNumberMortgagees { get; set; }
        public int? RedemptionNumberRequested { get; set; }
        public int? RedemptionNumberReceived { get; set; }
        public int? RedemptionNumberOutstanding { get; set; }
        public decimal? RedemptionTotalValue { get; set; }
        public int? RedStatNumberRequested { get; set; }
        public int? RedStatNumberReceived { get; set; }
        public int? RedStatNumberOutstanding { get; set; }
        public int? RedemptionNumberRedeemed { get; set; }
        public string CompletionAlternativeAddress1 { get; set; }
        public string CompletionAlternativeAddress2 { get; set; }
        public string CompletionAlternativeAddress3 { get; set; }
        public string CompletionAlternativeAddress4 { get; set; }
        public string CompletionAlternativeAddressPc { get; set; }
        public string DefaultClient { get; set; }
        public string LinkedCaseEntityRef { get; set; }
        public int? LinkedCaseMatterNo { get; set; }
        public string PreferredContactMethodClient { get; set; }
        public int? RemainingTerm { get; set; }
        public string Notes { get; set; }
        public string NotesCategory { get; set; }
        public DateTime? DateFileClosed { get; set; }
        public DateTime? CompletionTime { get; set; }
        public decimal? LinkedCasePurchasePrice { get; set; }
        public decimal? PurchaseProceeds { get; set; }
        public decimal? BalanceDueToClient { get; set; }
        public decimal? LinkedCasePurchaseProceeds { get; set; }
        public string TitleNumber { get; set; }
        public string CaseOwner { get; set; }
        public string PropertyRegistered { get; set; }
        public string TitleNumberThirdTitle { get; set; }
        public string TitleNumberSecondTitle { get; set; }
        public string RestrictionHolder1 { get; set; }
        public string RestrictionHolderAddress1 { get; set; }
        public string RestrictionHolderAddress2 { get; set; }
        public string RestrictionHolder2 { get; set; }
        public string AdditionalAccountNo { get; set; }
        public decimal? AdditionalMoney { get; set; }
        public string AdditionalSortcode { get; set; }
        public string AdditionalBranch { get; set; }
        public string QuestionnaireCompleted { get; set; }
        public string SameDayCompletion { get; set; }
        public decimal? MortgageInitialAmount { get; set; }
        public string SourceOfFunds { get; set; }
        public string SatisfactoryEvidenceReceived { get; set; }
        public string MortgageRequested { get; set; }
        public string PropertyToBeHeld { get; set; }
        public string StandardIndemnityCovenant { get; set; }
        public string BuyingThroughEstateAgent { get; set; }
        public decimal? DraftCompletionReceipts { get; set; }
        public decimal? DraftCompletionFunds { get; set; }
        public decimal? DraftCompletionTotalCosts { get; set; }
        public decimal? DraftCompletionBalance { get; set; }
        public DateTime? ExchangeTime { get; set; }
        public string PreciseTermsOfAgreedVariation { get; set; }
        public string CompletionAlternativeAddress5 { get; set; }
        public DateTime? OfficialCopyDate { get; set; }
        public decimal? AllowanceAmount { get; set; }
    }
}
